---@diagnostic disable: undefined-global

-- 服务端武器组合根。飞船入口只加载本文件，不直接认识任何具体武器。
#include "../shared/targeting/policy.lua"
#include "runtime/state/weapon_runtime.lua"
#include "runtime/loadout/slot_loadout.lua"
#include "runtime/loadout/slot_loadout_api.lua"
#include "runtime/damage.lua"
#include "runtime/effect_budget.lua"
#include "runtime/hotpath_budget_v1.lua"
#include "runtime/charged_ray_visual.lua"
#include "runtime/catalog/target_catalog.lua"
#include "runtime/registry/behavior_registry.lua"
#include "runtime/registry/controller_registry.lua"
#include "slot/t/render_state.lua"

#include "behavior/support/common.lua"
#include "behavior/raycast/support.lua"
#include "behavior/raycast/control.lua"
#include "behavior/raycast/inferno.lua"
#include "behavior/projectile/control.lua"
#include "behavior/guided_projectile/runtime.lua"
#include "behavior/guided_projectile/behavior.lua"
#include "behavior/strike_craft/behavior.lua"
#include "runtime/state/weapon_group.lua"

#include "runtime/control/main_weapon_control.lua"
#include "runtime/control/main_weapon_control_api.lua"
#include "slot/x/render_state.lua"
#include "slot/x/muzzle_light.lua"
#include "behavior/charged_ray/control.lua"
#include "behavior/charged_ray/state.lua"
#include "behavior/guided_projectile/runtime_state.lua"
#include "behavior/guided_projectile/movement.lua"
#include "behavior/guided_projectile/collision_budget_v1.lua"
#include "behavior/guided_projectile/collider.lua"
#include "behavior/guided_projectile/launcher_group.lua"
#include "behavior/guided_projectile/launcher/m.lua"
#include "behavior/guided_projectile/launcher/g.lua"
#include "behavior/strike_craft/flight_controller.lua"
#include "behavior/strike_craft/control.lua"
#include "behavior/point_defense/control.lua"
#include "behavior/point_defense/allocator_v1.lua"
#include "behavior/projectile/manager.lua"
#include "behavior/projectile/shield_broadphase_v1.lua"
#include "behavior/projectile/lifecycle_api_v1.lua"
#include "behavior/projectile/slot_control.lua"
#include "behavior/projectile/state.lua"

-- 适配器必须最后加载，确保它引用的旧控制器均已定义。
#include "runtime/control/controller_adapters.lua"
#include "network/weapon_command_endpoint.lua"
